apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.4.5
        args:
        - --source=ingress
        - --domain-filter=theddsandbox.com
        - --provider=aws
        - --registry=txt
        - --txt-owner-id=stakater
      serviceAccountName: external-dns