apiVersion: v1
kind: ConfigMap
metadata:
  name: external-ingress
  labels:
    app: external-ingress-lb
    k8s-addon: ingress-nginx.addons.k8s.io
data:
  enable-vts-status: 'true'
  use-proxy-protocol: "false"