apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    provider: fabric8
    project: exposecontroller
    version: 4.0.197
    group: io.fabric8.platform.apps
  name: exposecontroller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: exposecontroller-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: exposecontroller
    namespace: tools