apiVersion: v1
kind: ServiceAccount
metadata:
  name: exposecontroller
  namespace: internal
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: exposecontroller-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - delete
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: exposecontroller-role
  namespace: internal
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - delete
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: exposecontroller-role-nisa-binding
  namespace: internal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exposecontroller-role
subjects:
  - kind: ServiceAccount
    name: exposecontroller
    namespace: internal
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: exposecontroller-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: exposecontroller-clusterrole
subjects:
  - kind: ServiceAccount
    name: exposecontroller
    namespace: internal